name: app
type: "python:3.11" # 使用する Python のバージョン
build:
  flavor: python

dependencies:
  python:
    pip: "23.1" # 必要に応じて pip のバージョンを指定

web:
  commands:
    start: "python api.py" # アプリの起動コマンド
  locations:
    "/":
      passthru: true
      allow: true

mounts:
  "/var/log": "shared:files/log"

relationships:
  database: "db:mysql"

disk: 1024
